language: python
python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master
    - beta
    - develop

env:
    - Default=True  # construction, io, objects, tools, optimize, algorithms
    - ReportA=True  # Only testReport.py (none of the other reports tests)
    - ReportB=True  # test the other reports tests
    - Drivers=True  # All of drivers

# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y gfortran libblas-dev liblapack-dev
  # See here: http://lsi.ugr.es/~jmantas/pdp/ayuda/datos/instalaciones/Install_OpenMPI_en.pdf
  - sudo apt-get -qq install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev
  - sudo apt-get -qq install -y texlive-full 
  - sudo apt-get -qq install texlive-latex-extra # Not in texlive full? We'll see!
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start
install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install cvxpy python-pptx ruamel.yaml mpi4py
  - pip install -e .
  
cache: 
  pip: true
  timeout: 1000
# command to run tests
script:
  - cd test
  - travis_wait 40 python travisTests.py # Tests may take some time!
  - cd ..

after_success:
  - cd hooks/travis
  - ./after_success
  - cd ../..

after_failure:
  - cd hooks/travis
  - ./after_failure
  - cd ../..
