language: python
python:
  - "2.7"
branches:
  only:
    - master
    - unittests
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran libblas-dev liblapack-dev
install:
  - pip install -r requirements.txt
  - pip install cvxpy python-pptx
  - pip install -e .
# command to run tests
script:
  - cd test/test_tools/
  - python runPackage.py tools
