language: python
python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master
    - beta
    - develop

env:
    #- Default=True  # construction, io, objects, tools, optimize, algorithms
    #- ReportA=True  # Only testReport.py (none of the other reports tests)
    #- ReportB=True  # test the other reports tests
    #- Drivers=True  # All of drivers

# command to install dependencies
before_install:
  - sudo apt-get -qq update
# - sudo apt-get -qq install -y gfortran libblas-dev liblapack-dev
# See here: http://lsi.ugr.es/~jmantas/pdp/ayuda/datos/instalaciones/Install_OpenMPI_en.pdf
# - sudo apt-get -qq install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev
  - sudo apt-get -qq install -y texlive-full 
  - sudo apt-get -qq install texlive-generic-extra # Not in texlive full? We'll see!
  - sudo apt-get -qq install texlive-latex-extra 
#  - sudo apt-get install apt-file
#  - sudo apt-file update
#  - sudo apt-file search adjustbox.sty
#  - sudo locate texmf
  - pushd /usr/share/texmf-texlive/tex/latex
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/etoolbox.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/adjustbox.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/collectbox.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/pdfcomment.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/datetime2.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/generic/tracklang.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/bezos.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/hyperref.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/oberdiek.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/generic/ifxetex.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/standalone.tds.zip
  - sudo unzip etoolbox.tds.zip
  - sudo unzip adjustbox.tds.zip
  - sudo unzip collectbox.tds.zip
  - sudo unzip pdfcomment.tds.zip
  - sudo unzip datetime2.tds.zip
  - sudo unzip tracklang.tds.zip
  - sudo unzip bezos.tds.zip
  - sudo unzip hyperref.tds.zip
  - sudo unzip oberdiek.tds.zip
  - sudo unzip ifxetex.tds.zip
  - sudo unzip standalone.tds.zip
  - sudo texhash 
  - popd

#  - sudo tlmgr install adjustbox
#  - sudo tlmgr install collectbox
#  - sudo tlmgr install ucs
#  - sudo tlmgr install etoolbox
#  - sudo tlmgr install standalone
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start
install:
    - echo "DONE"
# - travis_retry travis_wait pip install -r requirements.txt
# - pip install cvxpy python-pptx mpi4py
# - pip install -e .
  
#cache: 
#  pip: true
#  timeout: 1000
# command to run tests
script:
  - cd test
  - cd test_packages/cmp_chk_files
    #- travis_wait 40 python travisTests.py # Tests may take some time!
  - pdflatex full_reportA.tex
  - cd ..

after_success:
  - cd hooks/travis
  - ./after_success
  - cd ../..

after_failure:
  - cd hooks/travis
  - ./after_failure
  - cd ../..
