language: python
python:
  - "2.7"
  - "3.5"
branches:
  only:
    - master
    - beta
    - develop
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran libblas-dev liblapack-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start
install:
  - pip install -r requirements.txt
  - pip install cvxpy python-pptx
  - pip install -e .
# command to run tests
script:
  - cd test
  - python travisTests.py 

after-success:
  - cd hooks/travis
  - ./after_success

after-failure:
  - cd hooks/travis
  - ./after_failure
