language: python

python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master
    - beta
    - develop

env:
    - Drivers=True  # All of drivers (Tends to take longer, put it first in the mx)
    - Default=True  # construction, io, objects, tools, optimize, algorithms
    - ReportA=True  # Only testReport.py (none of the other reports tests)
    - ReportB=True  # test the other reports tests
    - MPI=True  # All of MPI
   
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gfortran libblas-dev liblapack-dev >/dev/null
  - sudo apt-get -qq install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev >/dev/null
  - sudo bash CI/install.sh # Only install texlive and extensions if we need them
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start

install:
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install cvxpy cvxopt python-pptx mpi4py zmq coverage >/dev/null
  - pip install -e . >/dev/null
  
cache:
  pip: true
  timeout: 1000

script:
  - cd test
  - travis_wait 50 python travisTests.py # Tests may take some time!
  - cd ..

after_script:
    - |
        declare exitCode
        
        curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
        exitCode=$?

        if [ $exitCode -eq 0 ]; then
            python CI/deploy
        fi

        if [ $exitCode -eq 1 ]; then
            echo "Build failed - not deploying!!!!!!"
        fi

deploy:
  - provider: pypi
    user: enielse
    password:
      secure: CefzPGiJxOMN6jJPBj1/ORir+qWQsVdF6pVS/kzyT+XzCGAfOyRwq93Nxw+zXuFTZ49ycDEq3QFSpicVswVoZsyX6JUV2tn2ggblwJ/+pPYiYGSjDoEAaxih1FQ265zUTOgKWFjNt9ZN3V359dhOVKP1KdRQPYTJpDZlmKQrdCOiLp4sFuonAdfuKxlYQWt/P4N/THDS71l+muG0e0h7mfb8L9mdrQrgDXUGBqpf0PUdoaH13qsIyeatzPCYXfyzxiw/jPAxloM48BluDLS6xuNvUiuN09ry5Ie5iJ/Sc8Sen6U3MmxYDURUHWtjvr0q2BkJcQ3X2DODjCirdiMBILI3tY+oOolOphN6eiKc+ntOvuB0Vf/w5Z+VEpGOQAWYMOJX772Pv83r07BBBTJoh8q7XU5fOLyFk2hD0s7/3ASmzkNYqUHCGL5tACUT8nMVIaNfCX9gKhxX+oFpDfBhps23dTZnz1hDK3odmXp1t+UNpVOqfpgIfoBIsvfBRbyVfoYGxp3dMaSo6MOXEOzdw506UfjblzAw7+dy/vueOTQdFIBH9Z+UZmUwJ+F6uDkiJf4KBPdx+Ex8jzcmBzh6vsG95FBbOhHmbqOknCHJO2MZvBxY0uI+EaxjoTFVnXgeW99v/pca9vsLmEON5Mg1XgDC4T2F7od2XmUTebGIbhk=
    on:
        branch: master


notifications:
    email:
        on_success: change
        on_failure: always


