dist: trusty
language: python

python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master
    - beta
    - develop

env:
    - Drivers=True    # First in build mx because long duration
    - Algorithms=True 
    - AlgorithmsB=True
    - Default=True    # construction, io, objects, tools, optimize
    - Report=True      
    - ReportB=True
    - MPI=True        

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gfortran libblas-dev liblapack-dev
  - sudo apt-get -qq install openmpi-bin openmpi-common openssh-client openssh-server libopenmpi1.6 libopenmpi1.6-dbg libopenmpi-dev > /dev/null
  - sudo bash CI/install.sh # travis_wait 30 "sudo bash CI/install.sh" # > /dev/null 2>&1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start

install:
  - pip install zmq coverage >/dev/null
  - pip install -e .[travisci]
  
cache:
  pip: true
  timeout: 1000

#Script For default "test" stage
script:
  - cd test
  - python travisTests.py # just produce test_packages/runTravisTests.sh
  - cd test_packages
  - source runTravisTests.sh # no need for travis_wait (always outputs every 9m)
  - cd ../..

jobs:
  include:
    - stage: deploy
      python: 3.5
      env: Drivers=False Algorithms=False AlgorithmsB=False Default=False Report=False ReportB=False MPI=False
      script: python CI/deploy

notifications:
    email:
        on_success: change
        on_failure: always

