language: python

python:
  - "2.7"
  - "3.5"

branches:
  only:
    - master
    - beta
    - develop

env:
    - Default=True  # construction, io, objects, tools, optimize, algorithms
    - ReportA=True  # Only testReport.py (none of the other reports tests)
    - ReportB=True  # test the other reports tests
    - Drivers=True  # All of drivers
    - MPI=True  # All of MPI
   
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install gfortran libblas-dev liblapack-dev &>/dev/null
  - sudo apt-get -qq install openmpi-bin openmpi-common openssh-cli#ent openssh-server libopenmpi1.3 libopenmpi-dbg libopenmpi-dev &>/dev/null
  - sudo apt-get -qq install texlive-full &>/dev/null
  - pushd /usr/share/texmf-texlive/
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/etoolbox.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/adjustbox.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/collectbox.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/pdfcomment.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/datetime2.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/generic/tracklang.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/bezos.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/hyperref.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/oberdiek.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/generic/ifxetex.tds.zip
  - sudo wget http://mirrors.ctan.org/install/macros/latex/contrib/standalone.tds.zip
  - sudo unzip -o etoolbox.tds.zip &>/dev/null
  - sudo unzip -o adjustbox.tds.zip &>/dev/null
  - sudo unzip -o collectbox.tds.zip &>/dev/null
  - sudo unzip -o pdfcomment.tds.zip &>/dev/null
  - sudo unzip -o datetime2.tds.zip &>/dev/null
  - sudo unzip -o tracklang.tds.zip &>/dev/null
  - sudo unzip -o bezos.tds.zip &>/dev/null
  - sudo unzip -o hyperref.tds.zip &>/dev/null
  - sudo unzip -o oberdiek.tds.zip &>/dev/null
  - sudo unzip -o ifxetex.tds.zip &>/dev/null
  - sudo unzip -o standalone.tds.zip &>/dev/null
  - sudo texhash  &>/dev/null
  - popd
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" #some tests require a display
  - sleep 3 # give xvfb some time to start

install:
  - echo Hello
  - travis_retry travis_wait pip install -r requirements.txt
  - pip install cvxpy cvxopt python-pptx mpi4py zmq &>/dev/null
  - pip install -e . &>/dev/null
  
cache:
  pip: true
  timeout: 1000

script:
  - cd test
  - travis_wait 40 python travisTests.py # Tests may take some time!
  - cd ..

deploy:
    provider: script
    script: hooks/travis/deploy
    on:
        branch: develop


notifications:
    email:
        #recipients:
        #    - lucassaldyt@gmail.com # This would override sending only to commit author
        on_success: change
        on_failure: always

# This comment shouldn't end up in beta branch, since it is new
# Actually, the following command is required first...
# git config --global merge.ours.driver true
