# Adjustable settings set to defaults
adjustables:
  too-many-arguments: 
      max-args=10

  too-many-boolean-expressions: 
      max-bool-expr=5

  too-many-branches:
      max-branches=10

  too-many-instance-attributes:
      max-attributes=6

  too-many-locals:
      max-locals=15

  too-many-return-statements:
      max-returns=6

  too-many-statements:
      max-statements=100 

blacklisted-errors:
  - function-redefined           # This happens to be allowed in our repository! (Should it be?)
  - no-member                    # You could also blacklist each affected module/class in .lint.conf

blacklisted-warnings:
  - pointless-string-statement   # Around here, these usually serve as documentation :)
  - wildcard-import              # These might be fine for now, there are more important things
