# Adjustable settings set to defaults
adjustables:
  too-many-arguments: 
      max-args=10

  too-many-boolean-expressions: 
      max-bool-expr=5

  too-many-branches:
      max-branches=10

  too-many-instance-attributes:
      max-attributes=6

  too-many-locals:
      max-locals=15

  too-many-return-statements:
      max-returns=6

  too-many-statements:
      max-statements=100 
